import { betterAuth } from "better-auth";
import { magicLink } from "better-auth/plugins";
import { apiKey } from "@better-auth/api-key";
import { passkey } from "@better-auth/passkey";

/**
 * Auth, as better-auth ships it.
 *
 * Nothing here wraps the library: no hand-rolled session handling, no raw SQL
 * against its tables, no custom token minting. The schema these plugins need is
 * generated by better-auth's own CLI and folded into migrations/0001_rebuild.sql,
 * so the database and the library agree by construction rather than by
 * maintenance.
 *
 * Plugins:
 *   magicLink — the proven sign-in path.
 *   passkey   — second factor-free sign-in, same session machinery.
 *   apiKey    — the agent-native surface (#3905). Included now purely so its
 *               table lands in 0001_rebuild.sql and P3 needs no migration.
 */
type AuthEnv = {
  DB: D1Database;
  EMAIL: { send(message: unknown): Promise<unknown> };
  BETTER_AUTH_SECRET?: string;
  BETTER_AUTH_URL?: string;
};

export function createAuth(env: AuthEnv) {
  return betterAuth({
    // The binding goes in directly: @better-auth/kysely-adapter duck-types
    // batch/exec/prepare and supplies its own D1SqliteDialect, so no separate
    // D1 dialect dependency is needed (verified at dist/index.mjs:102).
    database: env.DB,
    secret: env.BETTER_AUTH_SECRET,
    baseURL: env.BETTER_AUTH_URL,
    plugins: [
      magicLink({
        // One send, through the platform binding. better-auth mints and
        // verifies the token; this only carries it. Transactional, so no
        // List-Unsubscribe header — that belongs on the weekly brief.
        sendMagicLink: async ({ email, url }) => {
          await env.EMAIL.send({
            to: email,
            from: { email: "hello@0509.io", name: "Five to Nine" },
            subject: "Your sign-in link",
            text: [
              "Sign in to Five to Nine:",
              "",
              url,
              "",
              "The link works once and expires shortly.",
              "If you did not ask for it, ignore this email.",
            ].join("\n"),
          });
        },
      }),
      passkey(),
      apiKey(),
    ],
  });
}

export type Auth = ReturnType<typeof createAuth>;
