import { betterAuth } from "better-auth";
import { magicLink } from "better-auth/plugins";
import { apiKey } from "@better-auth/api-key";
import { passkey } from "@better-auth/passkey";

/**
 * Auth, as better-auth ships it.
 *
 * Nothing here wraps the library: no hand-rolled session handling, no raw SQL
 * against its tables, no custom token minting. The schema these plugins need is
 * generated by better-auth's own CLI and folded into migrations/0001_rebuild.sql,
 * so the database and the library agree by construction rather than by
 * maintenance.
 *
 * Plugins:
 *   magicLink — the proven sign-in path.
 *   passkey   — second factor-free sign-in, same session machinery.
 *   apiKey    — the agent-native surface (#3905). Included now purely so its
 *               table lands in 0001_rebuild.sql and P3 needs no migration.
 */
export function createAuth(env: { DB: D1Database; BETTER_AUTH_SECRET?: string; BETTER_AUTH_URL?: string }) {
  return betterAuth({
    // The binding goes in directly: @better-auth/kysely-adapter duck-types
    // batch/exec/prepare and supplies its own D1SqliteDialect, so no separate
    // D1 dialect dependency is needed (verified at dist/index.mjs:102).
    database: env.DB,
    secret: env.BETTER_AUTH_SECRET,
    baseURL: env.BETTER_AUTH_URL,
    plugins: [
      magicLink({
        sendMagicLink: async () => {
          // Wired to the EMAIL binding in the delivery slice; the plugin owns
          // token minting and verification either way.
        },
      }),
      passkey(),
      apiKey(),
    ],
  });
}

export type Auth = ReturnType<typeof createAuth>;
