/**
 * Named barrel for D1 persistence. Product importers and Vitest mocks should
 * keep using `~/lib/data.server`. Domain leaves live under `~/lib/data/*` and
 * must not import this barrel (cycle).
 *
 * Phase 6b complete: all domain implementations moved to leaves. This file is
 * re-exports only (plus helpers `nowIso` / `createId`).
 */

export { nowIso, createId } from "~/lib/data/helpers.server";

export {
  listAdsByIds,
  replaceAnalysisFields,
  hydrateAdsWithPersistedCreatives,
  upsertAd,
  createLandingPageSnapshot,
  upsertDiscoveryCacheEntry,
  getDiscoveryCacheEntry,
  createDiscoveryFetchLog,
  upsertDiscoveryProviderState,
  getDiscoveryProviderState,
} from "~/lib/data/ads.server";

export {
  listWatchlistsPage,
  listWatchlists,
  listActiveWatchlistsPage,
  listActiveWatchlists,
  getWatchlist,
  createWatchlistWithinLimit,
  createWatchlist,
  deleteUnscannedWatchlistCreatedByFailedAgentAction,
  updateWatchlist,
  setWatchlistActive,
  listWebMentionTargets,
  listWebMentionObservations,
  syncWebMentionTargetsForUser,
  type CreateWatchlistInput,
  type CreateWatchlistWithinLimitResult,
  deactivateWatchlistsBeyondPlanLimit,
  reactivateWatchlistsUpToPlanLimit,
  hasInFlightWatchlistRun,
  listWatchlistRunPairsForEventIds,
  listFirstScanRunStates,
  type FirstScanRunState,
  createWatchlistRun,
  finishWatchlistRun,
  getRecentSuccessfulRuns,
  buildCapacitySkipIdempotencyKey,
  recordWatchlistCapacitySkip,
  listWatchlistRuns,
  touchWatchlistScanned,
  isSoftScanFailure,
  countLeadingFailures,
  getSuccessfulRunStatsForUserBetween,
  countWatchlistRunsForUserSince,
  createAdObservation,
  listObservationsForRunPage,
  listObservationsForRun,
  legacyWatchEventImportanceScore,
  listWatchEvents,
  listWatchEventsByIds,
  listEventCandidates,
  listWatchEventsBetween,
  createWatchEvent,
  createEventCandidate,
  getProofTargetByIdentity,
  upsertProofTarget,
  listProofCapturesForTarget,
  listProofCapturesForTargets,
  listProofCapturePairsForEventIds,
  listSuccessfulProofCapturesForAd,
  listLastSuccessfulProofCapturesForAds,
  listRecentProofCapturesForWatchlist,
  countProofCapturesForWatchlistSince,
  countProofCapturesForWorkspaceSince,
  countRecentSucceededProofScreenshotShare,
  getSuccessfulProofCaptureStatsForUser,
  listRecentWorkspaceProofCaptures,
  createProofCapture,
  getWatchlistDeliveryConfig,
  upsertWatchlistDeliveryConfig,
  beginWebsiteSiteScan,
  upsertWebsiteSiteScanPage,
  upsertWebsitePageObservation,
  finalizeWebsiteSiteScan,
  listWebsiteSiteScanPagesForRun,
  listWebsitePageObservationsForRun,
  getLatestCompleteWebsiteScanBaseline,
  type BeginWebsiteSiteScanInput,
  type UpsertWebsiteSiteScanPageInput,
  type UpsertWebsitePageObservationInput,
  type FinalizeWebsiteSiteScanInput,
  type WebsiteScanLease,
  type WebsiteSiteScanBaseline,
  type ObservationRow,
} from "~/lib/data/watchlists.server";

export {
  listRecentWorkspaceWatchEvents,
  listWatchEventsPage,
  listWatchEventsForRun,
} from "~/lib/data/watch-events.server";

export {
  grantProofUsageCredit,
  grantDodoPlanAccess,
  DODO_WEBHOOK_PROCESSING_LEASE_MS,
  applyDodoCancellationReversalWithLedger,
  applyDodoPlanGrantWithWatchlistReconcile,
  applyDodoPlanRevokeWithWatchlistReconcile,
  applyDodoRefundWithWatchlistReconcile,
  applyDodoPlanPaymentIssueWithLedger,
  applyDodoProofCreditGrantWithLedger,
  finalizeDodoWebhookLedgerOnly,
  DODO_PLAN_CHECKOUT_LOCK_MINUTES,
  DODO_SUBSCRIPTION_PLAN_CHANGE_LOCK_MINUTES,
  DODO_SUBSCRIPTION_PLAN_CHANGE_PENDING_STATUS,
  DODO_SUBSCRIPTION_PLAN_CHANGE_SCHEDULED_STATUS,
  isDodoSubscriptionPlanChangeStatus,
  isBlockingDodoSubscriptionPlanChangeStatus,
  claimDodoSubscriptionPlanChange,
  clearDodoSubscriptionPlanChangeClaim,
  markDodoSubscriptionPlanChangeScheduled,
  isDodoSubscriptionPlanChangeReconciliationDue,
  listStaleDodoSubscriptionPlanChangeClaims,
  reconcileDodoSubscriptionPlanChangeWithAudit,
  type DodoPlanChangeReconciliationInput,
  type DodoPlanChangeReconciliationOutcome,
  claimDodoPlanCheckout,
  clearDodoPlanCheckout,
  revokeDodoPlanAccess,
  beginDodoWebhookEventProcessing,
  claimDodoWebhookEvent,
  failDodoWebhookEventProcessing,
  failDodoWebhookEventForLifecycleEmailRetry,
  markDodoWebhookEventFinished,
  markDodoPlanPaymentIssue,
  revokeDodoAccessForRefundedPayment,
  getUserIdForDodoPayment,
  getUserIdForDodoLifecycle,
  getUserPlanBillingInfo,
  type DodoWebhookLedgerOutcome,
  type DodoWebhookLedgerFinalize,
  type DodoWebhookProcessingClaim,
  type UserPlanBillingInfo,
} from "~/lib/data/billing.server";

export {
  listPendingPartialRefundReconciliations,
  partialRefundLedgerKey,
  partialRefundReconciliationKey,
  reconcilePartialRefundWithAudit,
  type PartialRefundReconciliationDecision,
  type PendingPartialRefundReconciliation,
} from "~/lib/data/billing-refund-reconciliation.server";

export {
  legacyWorkspaceDeliveryDefaults,
  ensureNewWorkspaceDeliveryDefaults,
  migrateAutoProvisionedEmailTargets,
  listRetryableInstantAttempts,
  listStaleBillingLifecycleEmailAttempts,
  listOutstandingBillingLifecycleProviderUnknownAttempts,
  listOutstandingDigestProviderUnknownAttempts,
  listOutstandingInstantProviderUnknownAttempts,
  getWorkspaceDeliveryConfig,
  upsertWorkspaceDeliveryConfig,
  listDeliveryTargets,
  hasSuppressedEmailTargetForUserAndAddress,
  provisionVerifiedAccountEmailTargetIfUnsuppressed,
  getDeliveryTargetReadinessStats,
  upsertDeliveryTarget,
  getDeliveryTargetById,
  getDeliveryTargetByProviderIdentifier,
  claimEmailTargetForDispatch,
  suppressEmailTargetsForUserAndAddress,
  resumeEmailTargetsForUserAndAddress,
  reconcileWhatsAppSetupTargetFromAttempt,
  reconcileWhatsAppSetupTargetByProviderMessageId,
  getUserDeliveryProfile,
  listDeliveryAttempts,
  getDeliveryAttemptByIdempotencyKey,
  claimInstantDeliveryAttempt,
  markInstantDeliveryDispatchStarted,
  reconcileDeliveryAttemptByProviderMessageId,
  createDeliveryAttempt,
  updateDeliveryAttemptResult,
  buildBillingLifecycleOutboxStatement,
  type BillingLifecycleEmailOutboxSpec,
  type BillingLifecycleOutboxGate,
  type InstantDeliveryAttemptClaimInput,
} from "~/lib/data/delivery-records.server";

export {
  listBillingLifecycleReconciliationCandidates,
  reconcileBillingLifecycleEmailAttempt,
  type BillingLifecycleEmailReconciliationInput,
  type BillingLifecycleEmailReconciliationResult,
  type BillingLifecycleReconciliationCandidate,
  type BillingLifecycleReconciliationOutcome,
} from "~/lib/data/billing-lifecycle-reconciliation.server";

export {
  cleanupLaunchReadinessCanary,
  type LaunchCanaryCleanupInput,
  type LaunchCanaryCleanupResult,
} from "~/lib/data/launch-canary-cleanup.server";

export {
  DIGEST_ITEM_SET_PROVENANCE,
  claimDigestStrategyGenerationLease,
  completeDigestStrategyGeneration,
  createDigestRun,
  clearDigestItems,
  addDigestItem,
  upsertDigestDelivery,
  updateDigestRunSummary,
  listDigests,
  getDigest,
  getDigestByPeriod,
  getLatestDigestRunSummaryForWatchlist,
  listRetryableDigestRuns,
  enqueueDigestScheduleJobs,
  listRetryableDigestScheduleJobs,
  exhaustStaleMaxAttemptDigestScheduleJobs,
  claimDigestScheduleJob,
  completeDigestScheduleJob,
  failDigestScheduleJob,
  listExhaustedDigestScheduleJobs,
  listDigestScheduleJobsAwaitingAlert,
  claimDigestScheduleJobExhaustionAlert,
  settleDigestScheduleJobExhaustionAlert,
  type DigestScheduleJob,
} from "~/lib/data/digests.server";

export {
  createDigestScheduleJobRequeueKey,
  requeueExhaustedDigestScheduleJobWithAudit,
} from "~/lib/data/digest-schedule-recovery.server";

export {
  listCollectionsPage,
  listCollections,
  getCollection,
  createCollection,
  createCollectionWithinLimit,
  type CreateCollectionWithinLimitResult,
  listCollectionItemsPage,
  listCollectionItems,
  updateCollectionItem,
  addAdToCollection,
  addExternalProofToCollection,
  deleteCollection,
  deleteCollectionItem,
} from "~/lib/data/collections.server";

export {
  findAgentActionAuditByIdempotencyKey,
  listRecentAgentActionAudits,
  createAgentActionAudit,
  claimAgentActionAudit,
  reclaimRetryableAgentActionAudit,
  finishAgentActionAudit,
  closeCounterMoveFollowUp,
  upsertAgentMemory,
  listAgentMemory,
  listAgentMemoryForClientRooms,
  getClientRoom,
  getClientRoomByName,
  upsertClientRoom,
  listClientRooms,
  listCustomerApiKeys,
  insertCustomerApiKey,
  getActiveCustomerApiKeyByHash,
  isActiveCustomerApiKey,
  recordCustomerApiKeyUsed,
  revokeCustomerApiKey,
  getCustomerMetaConnection,
  upsertCustomerMetaConnection,
  updateCustomerMetaConnectionStatus,
  deleteCustomerMetaConnection,
} from "~/lib/data/customer-api.server";

export {
  SHARE_LINK_DEFAULT_TTL_DAYS,
  createShareLink,
  getShareLink,
  getShareLinkById,
  listActiveShareLinks,
  revokeShareLink,
} from "~/lib/data/shares.server";

export {
  createSupportCase,
  listSupportCases,
  getSupportCase,
  createSupportCaseEvent,
  listSupportCaseEvents,
} from "~/lib/data/support.server";

export {
  BILLING_EMAIL_EVIDENCE_CLASSIFICATIONS,
  INSTANT_SLACK_EVIDENCE_CLASSIFICATIONS,
  INSTANT_WHATSAPP_EVIDENCE_CLASSIFICATIONS,
  createBillingEmailReconciliationKey,
  createDigestEmailReconciliationKey,
  createInstantChannelReconciliationKey,
  createInstantEmailReconciliationKey,
  reconcileBillingEmailAttemptWithAudit,
  reconcileDigestEmailAttemptWithAudit,
  reconcileInstantChannelAttemptWithAudit,
  reconcileInstantEmailAttemptWithAudit,
  type BillingEmailEvidenceClassification,
  type InstantDeliveryChannel,
  type InstantDeliveryEvidenceClassification,
} from "~/lib/data/operator-delivery-reconciliation.server";

export {
  getOldestUserId,
  getUserIdByEmail,
  completeUserOnboarding,
  listSavedQueries,
  getSavedQuery,
  createSavedQuery,
  touchSavedQueryRun,
  WORKSPACE_BRAND_NAME_MAX_LENGTH,
  WORKSPACE_BRAND_WEBSITE_MAX_LENGTH,
  WORKSPACE_BRAND_LOGO_MAX_LENGTH,
  getWorkspaceBranding,
  normalizeWorkspaceBrandLogo,
  upsertWorkspaceBranding,
  type OperatorRiskSummary,
  type WeeklyBusinessSummary,
  getWeeklyBusinessSummary,
  getOperatorRiskSummary,
  getOperatorSnapshot,
  getOperatorSupportCase,
  logMetaIntegrationStatus,
  getMetaIntegrationStatus,
  getLaunchReadinessSignals,
} from "~/lib/data/workspace.server";
