/**
 * Named barrel for D1 persistence. Product importers and Vitest mocks should
 * keep using `~/lib/data.server`. Domain leaves live under `~/lib/data/*` and
 * must not import this barrel (cycle).
 *
 * Phase 6b complete: all domain implementations moved to leaves. This file is
 * re-exports only (plus helpers `nowIso` / `createId`).
 */

export { nowIso, createId } from "~/lib/data/helpers.server";

export {
  listAdsByIds,
  replaceAnalysisFields,
  hydrateAdsWithPersistedCreatives,
  upsertAd,
  createLandingPageSnapshot,
  upsertDiscoveryCacheEntry,
  getDiscoveryCacheEntry,
  createDiscoveryFetchLog,
  upsertDiscoveryProviderState,
  getDiscoveryProviderState,
} from "~/lib/data/ads.server";

export {
  listWatchlistsPage,
  listWatchlists,
  listActiveWatchlistsPage,
  listActiveWatchlists,
  getWatchlist,
  createWatchlistWithinLimit,
  createWatchlist,
  updateWatchlist,
  setWatchlistActive,
  listWebMentionTargets,
  listWebMentionObservations,
  syncWebMentionTargetsForUser,
  type CreateWatchlistInput,
  type CreateWatchlistWithinLimitResult,
  deactivateWatchlistsBeyondPlanLimit,
  reactivateWatchlistsUpToPlanLimit,
  hasInFlightWatchlistRun,
  createWatchlistRun,
  finishWatchlistRun,
  getRecentSuccessfulRuns,
  buildCapacitySkipIdempotencyKey,
  recordWatchlistCapacitySkip,
  listWatchlistRuns,
  touchWatchlistScanned,
  isSoftScanFailure,
  countLeadingFailures,
  getSuccessfulRunStatsForUserBetween,
  countWatchlistRunsForUserSince,
  createAdObservation,
  listObservationsForRunPage,
  listObservationsForRun,
  legacyWatchEventImportanceScore,
  listWatchEvents,
  listWatchEventsByIds,
  listEventCandidates,
  listWatchEventsBetween,
  createWatchEvent,
  createEventCandidate,
  getProofTargetByIdentity,
  upsertProofTarget,
  listProofCapturesForTarget,
  listProofCapturesForTargets,
  listSuccessfulProofCapturesForAd,
  listLastSuccessfulProofCapturesForAds,
  listRecentProofCapturesForWatchlist,
  countProofCapturesForWatchlistSince,
  countProofCapturesForWorkspaceSince,
  getSuccessfulProofCaptureStatsForUser,
  listRecentWorkspaceProofCaptures,
  createProofCapture,
  getWatchlistDeliveryConfig,
  upsertWatchlistDeliveryConfig,
  type ObservationRow,
} from "~/lib/data/watchlists.server";

export {
  grantProofUsageCredit,
  grantDodoPlanAccess,
  DODO_WEBHOOK_PROCESSING_LEASE_MS,
  applyDodoPlanGrantWithWatchlistReconcile,
  applyDodoPlanRevokeWithWatchlistReconcile,
  applyDodoRefundWithWatchlistReconcile,
  applyDodoPlanPaymentIssueWithLedger,
  applyDodoProofCreditGrantWithLedger,
  finalizeDodoWebhookLedgerOnly,
  DODO_PLAN_CHECKOUT_LOCK_MINUTES,
  DODO_SUBSCRIPTION_PLAN_CHANGE_LOCK_MINUTES,
  DODO_SUBSCRIPTION_PLAN_CHANGE_PENDING_STATUS,
  DODO_SUBSCRIPTION_PLAN_CHANGE_SCHEDULED_STATUS,
  isDodoSubscriptionPlanChangeStatus,
  isBlockingDodoSubscriptionPlanChangeStatus,
  claimDodoSubscriptionPlanChange,
  clearDodoSubscriptionPlanChangeClaim,
  markDodoSubscriptionPlanChangeScheduled,
  claimDodoPlanCheckout,
  clearDodoPlanCheckout,
  revokeDodoPlanAccess,
  beginDodoWebhookEventProcessing,
  claimDodoWebhookEvent,
  failDodoWebhookEventProcessing,
  failDodoWebhookEventForLifecycleEmailRetry,
  markDodoWebhookEventFinished,
  markDodoPlanPaymentIssue,
  revokeDodoAccessForRefundedPayment,
  getUserIdForDodoPayment,
  getUserIdForDodoLifecycle,
  getUserPlanBillingInfo,
  type DodoWebhookLedgerOutcome,
  type DodoWebhookLedgerFinalize,
  type DodoWebhookProcessingClaim,
  type UserPlanBillingInfo,
} from "~/lib/data/billing.server";

export {
  legacyWorkspaceDeliveryDefaults,
  migrateAutoProvisionedEmailTargets,
  listRetryableInstantAttempts,
  getWorkspaceDeliveryConfig,
  upsertWorkspaceDeliveryConfig,
  listDeliveryTargets,
  getDeliveryTargetReadinessStats,
  upsertDeliveryTarget,
  getDeliveryTargetById,
  getDeliveryTargetByProviderIdentifier,
  getUserDeliveryProfile,
  listDeliveryAttempts,
  getDeliveryAttemptByIdempotencyKey,
  reconcileDeliveryAttemptByProviderMessageId,
  createDeliveryAttempt,
  updateDeliveryAttemptResult,
} from "~/lib/data/delivery-records.server";

export {
  createDigestRun,
  clearDigestItems,
  addDigestItem,
  upsertDigestDelivery,
  updateDigestRunSummary,
  listDigests,
  getDigest,
  getDigestByPeriod,
  getLatestDigestRunSummaryForWatchlist,
  listRetryableDigestRuns,
} from "~/lib/data/digests.server";

export {
  listCollectionsPage,
  listCollections,
  getCollection,
  createCollection,
  listCollectionItemsPage,
  listCollectionItems,
  updateCollectionItem,
  addAdToCollection,
  addExternalProofToCollection,
  deleteCollection,
  deleteCollectionItem,
} from "~/lib/data/collections.server";

export {
  findAgentActionAuditByIdempotencyKey,
  listRecentAgentActionAudits,
  createAgentActionAudit,
  claimAgentActionAudit,
  finishAgentActionAudit,
  closeCounterMoveFollowUp,
  upsertAgentMemory,
  listAgentMemory,
  listAgentMemoryForClientRooms,
  getClientRoom,
  upsertClientRoom,
  listClientRooms,
  listCustomerApiKeys,
  insertCustomerApiKey,
  getActiveCustomerApiKeyByHash,
  recordCustomerApiKeyUsed,
  revokeCustomerApiKey,
  getCustomerMetaConnection,
  upsertCustomerMetaConnection,
  updateCustomerMetaConnectionStatus,
  deleteCustomerMetaConnection,
} from "~/lib/data/customer-api.server";

export {
  SHARE_LINK_DEFAULT_TTL_DAYS,
  createShareLink,
  getShareLink,
  getShareLinkById,
  listActiveShareLinks,
  revokeShareLink,
} from "~/lib/data/shares.server";

export {
  createSupportCase,
  listSupportCases,
  getSupportCase,
  createSupportCaseEvent,
  listSupportCaseEvents,
} from "~/lib/data/support.server";

export {
  getOldestUserId,
  getUserIdByEmail,
  completeUserOnboarding,
  listSavedQueries,
  getSavedQuery,
  createSavedQuery,
  touchSavedQueryRun,
  WORKSPACE_BRAND_NAME_MAX_LENGTH,
  WORKSPACE_BRAND_WEBSITE_MAX_LENGTH,
  WORKSPACE_BRAND_LOGO_MAX_LENGTH,
  getWorkspaceBranding,
  normalizeWorkspaceBrandLogo,
  upsertWorkspaceBranding,
  type OperatorRiskSummary,
  type WeeklyBusinessSummary,
  getWeeklyBusinessSummary,
  getOperatorRiskSummary,
  getOperatorSnapshot,
  logMetaIntegrationStatus,
  getMetaIntegrationStatus,
  getLaunchReadinessSignals,
} from "~/lib/data/workspace.server";
