import type { AdRecord, SearchMode } from "~/lib/types";

export const sampleQueries: Record<SearchMode, string[]> = {
  advertiser: ["nykaa", "mamaearth", "boat", "meesho"],
  keyword: ["cod", "free shipping", "festive sale", "whatsapp"],
};

export const indiaTags = [
  "English",
  "Hinglish",
  "Hindi",
  "regional",
  "discount",
  "bundle",
  "free shipping",
  "COD",
  "WhatsApp CTA",
  "app install",
  "festive",
  "creator-led",
  "UGC",
  "static",
  "video",
];

export const demoAds: AdRecord[] = [
  {
    metaAdId: "meta-nykaa-festive-001",
    advertiser: "Nykaa",
    body:
      "Glow Days are live. Upto 50% off on skin, makeup, and festive bundles with free shipping above Rs 599.",
    previewHeadline: "Festive glow, without the guesswork.",
    previewSubhead: "Upto 50% off and curated bundles for the next long weekend.",
    hook: "Your festive sale is only as strong as the first scroll-stop promise.",
    offer: "Upto 50% off and free shipping above Rs 599",
    cta: "Shop now",
    format: "video",
    languageLabel: "English",
    destinationType: "website",
    landingPageUrl: "https://nykaa.example.com/glow-days",
    adSnapshotUrl: "https://meta.example.com/ads/nykaa-festive-001",
    countries: ["India"],
    platforms: ["Instagram", "Facebook"],
    firstSeenAt: "2026-03-01T00:00:00.000Z",
    lastSeenAt: "2026-03-28T00:00:00.000Z",
    active: true,
    researchSummary: "Beauty retail ad using a clear sale promise and festive bundling instead of deep product education.",
    source: "demo",
    tags: ["English", "discount", "bundle", "video", "festive"],
    analysisFields: [],
    creativeText: "Festival Edit\nGlow kits from ₹599",
    creativeTextCaptureMethod: "manual",
    creativeTextMetadata: {
      reason: "demo_seed",
    },
    landingPage: {
      rawUrl: "https://nykaa.example.com/glow-days",
      canonicalUrl: "https://nykaa.example.com/glow-days",
      rawHeadline: "Glow Days Sale - Up to 50% Off",
      normalizedHeadline: "glow days sale - up to 50% off",
      normalizedHeadlineHash: "fnv1a-4d52f63b",
      captureMethod: "manual",
      capturedAt: "2026-03-28T09:00:00.000Z",
    },
  },
  {
    metaAdId: "meta-mamaearth-sunscreen-001",
    advertiser: "Mamaearth",
    body:
      "No white cast. No greasy feel. New vitamin C sunscreen with Rs 200 off on combo packs this week only.",
    previewHeadline: "Sunscreen that does not fight your routine.",
    previewSubhead: "Combo-led offer with creator testimonials and a clean pain-relief angle.",
    hook: "The ad sells relief first, not ingredients first.",
    offer: "Rs 200 off on combo packs",
    cta: "Buy combo",
    format: "image",
    languageLabel: "English",
    destinationType: "website",
    landingPageUrl: "https://mamaearth.example.com/vitamin-c-spf",
    adSnapshotUrl: "https://meta.example.com/ads/mamaearth-spf-001",
    countries: ["India"],
    platforms: ["Instagram", "Facebook"],
    firstSeenAt: "2026-02-17T00:00:00.000Z",
    lastSeenAt: "2026-03-27T00:00:00.000Z",
    active: true,
    researchSummary: "Classic DTC skincare pitch built around daily-use pain points and combo economics.",
    source: "demo",
    tags: ["English", "discount", "bundle", "static"],
    analysisFields: [],
    creativeText: "No white cast\nFlat ₹200 off",
    creativeTextCaptureMethod: "manual",
    creativeTextMetadata: {
      reason: "demo_seed",
    },
    landingPage: {
      rawUrl: "https://mamaearth.example.com/vitamin-c-spf",
      canonicalUrl: "https://mamaearth.example.com/vitamin-c-spf",
      rawHeadline: "Vitamin C Sunscreen Combo",
      normalizedHeadline: "vitamin c sunscreen combo",
      normalizedHeadlineHash: "fnv1a-953b4f73",
      captureMethod: "manual",
      capturedAt: "2026-03-27T09:30:00.000Z",
    },
  },
  {
    metaAdId: "meta-boat-neckband-001",
    advertiser: "boAt",
    body:
      "Bass bhi, battery bhi. Rockerz neckbands at launch pricing with COD available across India.",
    previewHeadline: "Bass bhi. Battery bhi.",
    previewSubhead: "Hinglish launch copy with COD reassurance and aggressive price framing.",
    hook: "The product promise lands because the offer and COD reassurance are inseparable.",
    offer: "Launch pricing with COD available",
    cta: "Buy now",
    format: "video",
    languageLabel: "Hinglish",
    destinationType: "website",
    landingPageUrl: "https://boat.example.com/rockerz-neckband",
    adSnapshotUrl: "https://meta.example.com/ads/boat-neckband-001",
    countries: ["India"],
    platforms: ["Instagram", "Facebook", "Messenger"],
    firstSeenAt: "2026-03-09T00:00:00.000Z",
    lastSeenAt: "2026-03-28T00:00:00.000Z",
    active: true,
    researchSummary: "Consumer electronics ad leaning on vernacular phrasing, urgency, and trust-building via COD.",
    source: "demo",
    tags: ["Hinglish", "COD", "video"],
    analysisFields: [],
    creativeText: "60 Hours Playback\nOnly ₹999",
    creativeTextCaptureMethod: "manual",
    creativeTextMetadata: {
      reason: "demo_seed",
    },
    landingPage: {
      rawUrl: "https://boat.example.com/rockerz-neckband",
      canonicalUrl: "https://boat.example.com/rockerz-neckband",
      rawHeadline: "boAt Rockerz Launch Offer",
      normalizedHeadline: "boat rockerz launch offer",
      normalizedHeadlineHash: "fnv1a-34fc44c8",
      captureMethod: "manual",
      capturedAt: "2026-03-28T08:50:00.000Z",
    },
  },
  {
    metaAdId: "meta-meesho-whatsapp-001",
    advertiser: "Meesho",
    body:
      "Earn from home with zero inventory. Join seller onboarding on WhatsApp and start sharing catalogues today.",
    previewHeadline: "Start from your phone, not a warehouse.",
    previewSubhead: "Marketplace acquisition creative pushing WhatsApp as the primary conversion path.",
    hook: "The ad is selling friction removal, not platform scale.",
    offer: "Zero inventory seller onboarding",
    cta: "WhatsApp now",
    format: "carousel",
    languageLabel: "English",
    destinationType: "whatsapp",
    landingPageUrl: "https://wa.me/919999999999",
    adSnapshotUrl: "https://meta.example.com/ads/meesho-seller-001",
    countries: ["India"],
    platforms: ["Facebook", "Instagram"],
    firstSeenAt: "2026-03-05T00:00:00.000Z",
    lastSeenAt: "2026-03-26T00:00:00.000Z",
    active: true,
    researchSummary: "Strong example of destination-specific analysis: the CTA path is itself part of the offer.",
    source: "demo",
    tags: ["WhatsApp CTA", "carousel"],
    analysisFields: [],
    landingPage: {
      rawUrl: "https://wa.me/919999999999",
      canonicalUrl: "https://wa.me/919999999999",
      rawHeadline: "WhatsApp Seller Onboarding",
      normalizedHeadline: "whatsapp seller onboarding",
      normalizedHeadlineHash: "fnv1a-6b7f30f0",
      captureMethod: "manual",
      capturedAt: "2026-03-26T08:10:00.000Z",
    },
  },
  {
    metaAdId: "meta-sugar-holi-001",
    advertiser: "SUGAR Cosmetics",
    body:
      "Holi glam packs with free minis and shade-safe kits. Limited-time creator drop before the weekend.",
    previewHeadline: "Holi looks, packed and ready.",
    previewSubhead: "Seasonal offer tied to creator energy instead of generic sale messaging.",
    hook: "Seasonality works because the pack is positioned as a ready-made ritual.",
    offer: "Free minis with Holi glam packs",
    cta: "Explore kits",
    format: "image",
    languageLabel: "English",
    destinationType: "website",
    landingPageUrl: "https://sugar.example.com/holi-glam-packs",
    adSnapshotUrl: "https://meta.example.com/ads/sugar-holi-001",
    countries: ["India"],
    platforms: ["Instagram"],
    firstSeenAt: "2026-03-02T00:00:00.000Z",
    lastSeenAt: "2026-03-24T00:00:00.000Z",
    active: false,
    researchSummary: "Useful example of a seasonal bundle angle that feels curated, not clearance-led.",
    source: "demo",
    tags: ["festive", "creator-led", "static"],
    analysisFields: [],
    landingPage: {
      rawUrl: "https://sugar.example.com/holi-glam-packs",
      canonicalUrl: "https://sugar.example.com/holi-glam-packs",
      rawHeadline: "Holi Glam Packs",
      normalizedHeadline: "holi glam packs",
      normalizedHeadlineHash: "fnv1a-1d77689e",
      captureMethod: "manual",
      capturedAt: "2026-03-24T07:55:00.000Z",
    },
  },
];
