import {
  BUYER_SURFACE_LOCALE_IDS,
  SNEAKER_RESALE_MARKETS,
  type BuyerSurfaceLocaleId,
} from "~/lib/locale-markets";
import {
  PUBLISHED_BUNDLE_PRICES_EUR,
  PUBLISHED_FREE_PLAN_OFFER,
  PUBLISHED_PLAN_PRICES_EUR,
  type PricingPlanSlug,
  type UsageBundleSlug,
} from "~/lib/pricing";
import { TOP_UP_PACK_DISPLAY } from "~/lib/billing-sku-catalog";

const SITE_ORIGIN = "https://0509.io";
const SITE_NAME = "Five to Nine";
// PNG, not SVG: most social scrapers (WhatsApp, Slack, X, iMessage) refuse
// SVG og:images. The legacy /social-card.svg stays served for cached links.
const SOCIAL_IMAGE_PATH = "/og-image.png";
const SOCIAL_IMAGE_URL = `${SITE_ORIGIN}${SOCIAL_IMAGE_PATH}`;
const LEGACY_SOCIAL_CARD_PATH = "/social-card.svg";
const SOCIAL_IMAGE_ALT = "Five to Nine competitor offer monitoring preview";

export function canonicalUrl(pathname: string): string {
  const normalizedPath = pathname.startsWith("/") ? pathname : `/${pathname}`;
  const pathOnly = normalizedPath.split(/[?#]/)[0] ?? "/";
  const withoutTrailingSlash =
    pathOnly === "/" ? pathOnly : pathOnly.replace(/\/+$/, "");

  return `${SITE_ORIGIN}${withoutTrailingSlash || "/"}`;
}

export function canonicalLinks(pathname: string) {
  return [{ rel: "canonical", href: canonicalUrl(pathname) }];
}

/**
 * Per-route social card URL builders (issue #1572). Each programmatic buyer
 * surface points its `og:image` at a dynamic SVG card served under
 * `/social-card/...` instead of the site-wide generic `og-image.png`. The
 * cards are generated by `app/lib/social-cards.server.ts` and served from
 * `workers/app.ts`; these helpers only build the absolute URL the route's
 * `meta` stamps, so a route never hardcodes the card path scheme.
 *
 * The ads card carries the brand display name and Ad Aggression Score as query
 * params (`n`, `s`) so the stateless SVG renderer can stamp them without a
 * second D1 read — the route's loader already computed them at page-render
 * time, so the score in the URL matches the page's current score. When the
 * score is deferred (null, < 14-day floor), `s` is omitted and the card shows
 * the brand without a number.
 */
export function adsSocialCardUrl(domain: string, brandName: string, score: number | null): string {
  const params = new URLSearchParams({ n: brandName });
  if (score !== null && Number.isFinite(score)) {
    params.set("s", String(score));
  }
  // canonicalUrl strips query strings (it splits on `?`), so build the
  // canonical path first and append the query params afterwards. The card is
  // served as PNG (issue #2089), so the path uses `.png`.
  return `${canonicalUrl(`/social-card/ads/${domain}.png`)}?${params.toString()}`;
}

export function timelineSocialCardUrl(domain: string, brandName: string): string {
  const params = new URLSearchParams({ n: brandName });
  // canonicalUrl strips query strings, so build the canonical path first and
  // append the brand query param afterwards (same recipe as the ads card).
  // The card is served as PNG (issue #2089), so the path uses `.png`.
  return `${canonicalUrl(`/social-card/timeline/${domain}.png`)}?${params.toString()}`;
}

export interface SearchShareMeta {
  title: string;
  description: string;
  ogImageUrl: string;
  ogImageAlt: string;
}

/**
 * Resolve the share meta for a `/search` result that settled on a single
 * competitor (issue #2039). The `/search` result page is the top-of-funnel
 * first-value share moment — a visitor shares a resolved competitor lookup
 * (DM/email/Social/Slack) before creating an account — so a resolved single
 * brand must render that brand's per-competitor social card and name it in
 * the title/description, instead of the site-wide generic `og-image.png`.
 *
 * resolution rule: a competitor counts as resolved only when a valid
 * `?website=` input normalized to exactly one brand — i.e. both `host` (the
 * card's domain slug) and `displayName` (the card face) are set. `?website=`
 * is the loader's only unambiguous single-brand signal: `competitorWebsite`
 * is never populated for a bare `?query=` keyword lookup, which may match many
 * brands, so gating on `displayName`+`host` keeps a wrong-brand card off an
 * ambiguous keyword hit. When nothing resolves (idle `/search`, invalid input,
 * multi-match keyword) returns `null` so the caller keeps the generic
 * "Find competitor ads" meta untouched.
 *
 * The returned `ogImageUrl` is the same encoded SVG card the `/ads/:domain`
 * surface already renders, so a shared search-result link carries the same
 * "the competitor is behind this" conviction as a shared brand page.
 */
export function searchShareMeta(input: {
  website: string | null;
  host: string | null;
  displayName: string | null;
  score?: number | null;
}): SearchShareMeta | null {
  const { website, host, displayName } = input;
  const score = input.score ?? null;
  if (!website || !host || !displayName) {
    return null;
  }
  const ogImageUrl = adsSocialCardUrl(host, displayName, score);
  const ogImageAlt = `${displayName} Meta ads — see what changed — Five to Nine`;
  return {
    title: `${displayName} Meta ads — see what changed | Five to Nine`,
    description: `Every public Meta ad ${displayName} is running right now — see what changed, compare offers, and track their spend. Free preview, no account needed.`,
    ogImageUrl,
    ogImageAlt,
  };
}

export function compareSocialCardUrl(toolSlug: string): string {
  return canonicalUrl(`/social-card/compare/${toolSlug}.svg`);
}

export function switchSocialCardUrl(toolSlug: string): string {
  return canonicalUrl(`/social-card/switch/${toolSlug}.svg`);
}

export function clusterSocialCardUrl(slug: "sneaker-resale" | "competitor-monitoring"): string {
  return canonicalUrl(`/social-card/${slug}.svg`);
}

/**
 * Social card URL for a `/brands/:category` landing page (issue #2067).
 * Mirrors `clusterSocialCardUrl`: the card is static SVG derived entirely
 * from the category slug, so the route's `meta` just stamps this absolute
 * URL. The card is generated by `app/lib/social-cards.server.ts` and served
 * from `workers/app.ts` under `/social-card/brand/<slug>.svg`.
 */
export function brandCategorySocialCardUrl(slug: string): string {
  return canonicalUrl(`/social-card/brand/${slug}.svg`);
}

/**
 * Canonical consolidation for the duplicate /compare/* pairs (issue #1481).
 *
 * Every entry maps a loser URL to the winner it must canonicalize to. The
 * winners (`visualping-ad-libraries`, `foreplay-spyder`) name the narrower
 * buyer intent, so the generic `vs Visualping` / `vs Foreplay` pages point
 * their `rel="canonical"` at them. Losers stay live HTTP-200 pages (existing
 * backlinks and /switch links keep working) but carry the winner canonical
 * and are dropped from the sitemap, so Google consolidates each pair instead
 * of splitting PageRank between two near-identical SERP targets.
 */
export const COMPARE_CANONICAL_TARGETS: Readonly<Record<string, string>> = {
  "/compare/visualping": "/compare/visualping-ad-libraries",
  // Singular was the pre-#1548 winner; the issue names the plural URL as the
  // page, so the plural is the winner and this singular stays a 200 loser.
  "/compare/visualping-ad-library": "/compare/visualping-ad-libraries",
  "/compare/foreplay": "/compare/foreplay-spyder",
};

/**
 * Reciprocal hreflang set for the sneaker-resale cluster, including self and
 * x-default (English). Google ignores one-way annotations.
 * https://developers.google.com/search/docs/specialty/international/localized-versions
 */
export function sneakerResaleHreflangLinks() {
  return [
    ...SNEAKER_RESALE_MARKETS.map((market) => ({
      rel: "alternate" as const,
      hreflang: market.hreflang,
      href: canonicalUrl(market.pathname),
    })),
    {
      rel: "alternate" as const,
      hreflang: "x-default",
      href: canonicalUrl("/sneaker-resale"),
    },
  ];
}

/**
 * Reciprocal hreflang set for the buyer-surface cluster (issue #1501).
 *
 * `splat` is the locale-prefix subpath (e.g. `"pricing"`, `"help"`, or
 * `""` for the locale index). The function emits self + sibling locale
 * entries pointing at the same subpath in each locale, plus the EN
 * (x-default) version. The buyer-surface cluster is broader than the
 * sneaker-resale cluster (fr/es are pre-evidence for the broader
 * marketing surface) and uses the same hreflang recipe.
 *
 * Google ignores one-way annotations, so the EN-side `rel=canonical`
 * pointing at the EN subpath does the heavy lifting; this function
 * exists so the cluster is reciprocal on both ends.
 */
export function buyerSurfaceHreflangLinks(splat: string) {
  const enPath = splat === "" ? "/" : splat === "api/docs" ? "/api/docs" : `/${splat}`;
  return [
    ...BUYER_SURFACE_LOCALE_IDS.map((locale) => ({
      rel: "alternate" as const,
      hreflang: locale,
      href: canonicalUrl(splat === "" ? `/${locale}` : `/${locale}/${splat}`),
    })),
    {
      rel: "alternate" as const,
      hreflang: "x-default",
      href: canonicalUrl(enPath),
    },
  ];
}

export function publicSeoMeta(input: {
  title: string;
  description: string;
  pathname: string;
  ogLocale?: string;
  /**
   * Per-route Open Graph image override (issue #1572). When set, the page
   * stamps this URL as `og:image` / `twitter:image` instead of the site-wide
   * generic `og-image.png`, so a programmatic buyer surface (`/ads/:domain`,
   * `/compare/*`, `/switch/*`, `/sneaker-resale`, `/competitor-monitoring`)
   * renders a page-specific branded card. Falls back to `SOCIAL_IMAGE_URL`
   * when unset so the generic card stays on truly site-wide surfaces.
   */
  ogImageUrl?: string;
  /**
   * Alt text for the per-route `og:image` override. Required when
   * `ogImageUrl` is set (the card must name the brand/tool per the issue's
   * acceptance). Ignored when `ogImageUrl` is unset.
   */
  ogImageAlt?: string;
}) {
  const url = canonicalUrl(input.pathname);
  const overrideImage = input.ogImageUrl;
  const overrideAlt = input.ogImageAlt;
  const imageUrl = overrideImage ?? SOCIAL_IMAGE_URL;
  const imageAlt = overrideImage ? (overrideAlt ?? SOCIAL_IMAGE_ALT) : SOCIAL_IMAGE_ALT;
  const imageType =
    overrideImage && new URL(overrideImage).pathname.endsWith(".svg")
      ? "image/svg+xml"
      : "image/png";

  return [
    { title: input.title },
    { name: "description", content: input.description },
    ...(input.ogLocale ? [{ property: "og:locale", content: input.ogLocale }] : []),
    { property: "og:site_name", content: SITE_NAME },
    { property: "og:type", content: "website" },
    { property: "og:title", content: input.title },
    { property: "og:description", content: input.description },
    { property: "og:url", content: url },
    { property: "og:image", content: imageUrl },
    { property: "og:image:type", content: imageType },
    { property: "og:image:width", content: "1200" },
    { property: "og:image:height", content: "630" },
    { property: "og:image:alt", content: imageAlt },
    { name: "twitter:card", content: "summary_large_image" },
    { name: "twitter:title", content: input.title },
    { name: "twitter:description", content: input.description },
    { name: "twitter:image", content: imageUrl },
    { name: "twitter:image:alt", content: imageAlt },
  ];
}

/**
 * `<meta name="robots" content="noindex">` descriptor for auth/action
 * surfaces that must never be Google-indexable: signup, login, magic-link
 * confirm, password-reset, billing portal. Auth surfaces leak the entry
 * point to scrapers, burn crawl budget, and can outrank `/` or `/auth/signup`
 * for branded "five to nine sign in" queries — so every rendering auth route
 * appends this entry to its `meta` array alongside its `publicSeoMeta(...)`
 * entries. The canonical tag stays (noindex is the correct fix, not removing
 * canonical); these surfaces also stay out of `SITEMAP_PATHS`. Shared here so
 * every auth route uses one source of truth instead of re-inlining the tag.
 */
export function noindexMetaEntry() {
  return { name: "robots", content: "noindex" } as const;
}

export interface FaqJsonLdEntry {
  question: string;
  answer: string;
}

/**
 * schema.org Organization for the landing page. Deliberately minimal — no
 * price amounts anywhere in structured data (prices are live-loaded from
 * Dodo in the buyer's currency and must never be hardcoded).
 */
export function organizationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: SITE_NAME,
    url: SITE_ORIGIN,
  } as const;
}

/** schema.org WebSite with the public search preview as the site search action.
 *
 * Uses schema.org `query-input: required name=search_term_string` (the
 * standard `q` template) so a Google sitelink substituting the visible
 * `nike` (or any other brand term) lands on `/search?q=nike` and runs the
 * same first-value search the visitor would get by typing it on the
 * homepage. The earlier `?website={website}` template was rejected as an
 * incomplete domain by `hasInvalidCompetitorWebsite`, so the search never
 * ran and the H1 stayed idle. Watchlist, onboarding, and the website form
 * field keep requiring a real domain — only the public sitelink-shaped
 * sitelink target now uses the search-term slot. */
export function webSiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: SITE_NAME,
    url: SITE_ORIGIN,
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${SITE_ORIGIN}/search?q={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
  } as const;
}

/**
 * schema.org FAQPage. Pass every FAQ block on the page in one call — Google
 * expects a single FAQPage entity per page, so the landing page combines the
 * product and billing FAQ entries into one mainEntity list.
 */
export function faqPageJsonLd(entries: ReadonlyArray<FaqJsonLdEntry>) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: entries.map((entry) => ({
      "@type": "Question",
      name: entry.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: entry.answer,
      },
    })),
  } as const;
}

export interface BreadcrumbJsonLdItem {
  name: string;
  pathname: string;
}

/**
 * schema.org BreadcrumbList. Pass the visible breadcrumb trail in page order
 * (Home first, current page last) — every entry's `item` URL is derived from
 * its pathname via `canonicalUrl` so the structured data can never drift from
 * the site's canonical URL scheme. The last entry is the current page; the
 * caller passes its real pathname so the `item` URL matches the page's
 * canonical tag.
 *
 * Google expects the `name` to match what the user sees in the visible
 * breadcrumb, so the caller must pass the same labels it renders.
 */
export function breadcrumbListJsonLd(
  items: ReadonlyArray<BreadcrumbJsonLdItem>,
) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: canonicalUrl(item.pathname),
    })),
  } as const;
}

export interface ItemListJsonLdEntry {
  name: string;
  pathname: string;
}

/**
 * schema.org ItemList for a browse-hub page that links a set of sibling
 * pages (issue #2215). The /brands hub lists every indexable /ads/:domain
 * brand page; wrapping that set in an ItemList tells Google the page is a
 * browsable collection and lets it connect the brand pages as a cluster
 * (collection rich results / internal-link graph) instead of reading a flat
 * page. Each ListItem's `item` URL is derived from its pathname via
 * `canonicalUrl` so the structured data can never drift from the site's
 * canonical URL scheme, and the `name` matches the visible link label.
 *
 * Emitted only when the hub actually lists brands — an empty hub renders no
 * ItemList (nothing to enumerate).
 */
export function itemListJsonLd(entries: ReadonlyArray<ItemListJsonLdEntry>) {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    itemListElement: entries.map((entry, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: entry.name,
      item: canonicalUrl(entry.pathname),
    })),
  } as const;
}

/**
 * schema.org WebPage for a public informational page. Deliberately plain: it
 * states only what the page already shows — its name, its description, and the
 * site it belongs to. The audit found no structured data on /help, /docs or
 * /status; this closes that without asserting anything the visible page does
 * not already say.
 *
 * The optional fields follow the same rule — they are emitted ONLY when the
 * visible page itself carries the claim:
 * - `dateModified`: the ISO timestamp of the last content update the page
 *   visibly stamps (e.g. the cached-check time on /ads/:domain). Omitted when
 *   the page has no such stamp — never invented.
 * - `datePublished`: the ISO timestamp of the FIRST stored snapshot for the
 *   page's subject (the day the record opened — e.g. the oldest
 *   `landing_page_snapshot.captured_at` the /ads/:domain page already renders
 *   in its Offer Timeline section). Omitted when nothing is stored, so a page
 *   with zero snapshots never claims a publication date.
 * - `aboutName`: the subject of the page when it is about a specific brand
 *   (e.g. the /ads/:domain brand pages). Must match a name the page shows.
 * - `comparedProductName`: the competitor product a `/compare/*` page is
 *   about. Emitted as `SoftwareApplication` `mainEntity` with only the name
 *   the page already shows — never ratings, prices, or review counts.
 */
export function webPageJsonLd(input: {
  name: string;
  description: string;
  pathname: string;
  dateModified?: string;
  datePublished?: string;
  aboutName?: string;
  comparedProductName?: string;
  /**
   * A `Dataset` (or other `CreativeWork`) this page has as a citable part.
   * The `/ads/:domain` brand page sets this to its Offer Timeline `Dataset`
   * when the page is indexable and a stored timeline exists, so answer
   * engines can follow the relationship from the brand page to the
   * change-ledger dataset (issue #964).
   */
  hasPart?: Record<string, unknown>;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: input.name,
    description: input.description,
    url: canonicalUrl(input.pathname),
    ...(input.datePublished ? { datePublished: input.datePublished } : {}),
    ...(input.dateModified ? { dateModified: input.dateModified } : {}),
    ...(input.aboutName
      ? { about: { "@type": "Organization", name: input.aboutName } }
      : {}),
    ...(input.comparedProductName
      ? {
          mainEntity: {
            "@type": "SoftwareApplication",
            name: input.comparedProductName,
          },
        }
      : {}),
    ...(input.hasPart ? { hasPart: input.hasPart } : {}),
    isPartOf: { "@type": "WebSite", name: SITE_NAME, url: SITE_ORIGIN },
    publisher: { "@type": "Organization", name: SITE_NAME, url: SITE_ORIGIN },
  } as const;
}

/**
 * schema.org BreadcrumbList for a public informational page. Emitted on
 * indexable multi-level pages (e.g. /timeline/:domain) so Google can show a
 * breadcrumb in the rich result. Every `item` is the canonical URL of the
 * corresponding pathname — the same canonical the page itself links — so the
 * crumbs can never point at a strayhost or query-parameter variant. The last
 * crumb is the page itself (its canonical URL), which the rich-results
 * validator accepts as the current position.
 */
export function breadcrumbJsonLd(input: {
  items: ReadonlyArray<{ name: string; pathname: string }>;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: input.items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: canonicalUrl(item.pathname),
    })),
  } as const;
}

/**
 * schema.org Article for a /guides/* editorial page (issue #2855). The
 * guide pages are how-to editorial content, so they carry an Article entity
 * alongside the WebPage + FAQPage they already emit. Every field mirrors
 * what the page itself renders: headline is the visible h1 text (the route
 * passes the same string constant it renders), description the meta
 * description, datePublished/dateModified the dates the page already states,
 * author and publisher the site organization.
 */
export function articleJsonLd(input: {
  headline: string;
  description: string;
  pathname: string;
  datePublished: string;
  dateModified?: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: input.headline,
    description: input.description,
    url: canonicalUrl(input.pathname),
    mainEntityOfPage: { "@type": "WebPage", "@id": canonicalUrl(input.pathname) },
    datePublished: input.datePublished,
    ...(input.dateModified ? { dateModified: input.dateModified } : {}),
    author: { "@type": "Organization", name: SITE_NAME, url: SITE_ORIGIN },
    publisher: { "@type": "Organization", name: SITE_NAME, url: SITE_ORIGIN },
  } as const;
}

/**
 * schema.org Service for a public category landing page (issue #2855 —
 * /competitor-monitoring). Mirrors `adsPageServiceJsonLd` but without a
 * per-domain about: the page offers the monitoring service itself, so the
 * entity carries only the service name, the meta description the page
 * already serves, its canonical URL, and Five to Nine as the provider. No
 * price, rating, or availability — prices are live-loaded from Dodo and
 * must never be hardcoded in structured data.
 */
export function serviceJsonLd(input: {
  name: string;
  description: string;
  pathname: string;
  serviceType?: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    name: input.name,
    description: input.description,
    url: canonicalUrl(input.pathname),
    ...(input.serviceType ? { serviceType: input.serviceType } : {}),
    provider: { "@type": "Organization", name: SITE_NAME, url: SITE_ORIGIN },
  } as const;
}

/**
 * schema.org Product+Offer pair for a /pricing tier or proof pack (#1503).
 *
 * Returns a single Product entity with one nested Offer; the Offer carries
 * the published stable EUR list price (PUBLISHED_PLAN_PRICES_EUR /
 * PUBLISHED_BUNDLE_PRICES_EUR) plus a priceValidUntil note that the figure
 * is the published list price, not the live Dodo Payments checkout amount
 * (which can drift by locale, SKU, and tax-inclusion settings). The
 * pricingOffersJsonLd() builder below emits one of these for every tier
 * card (Free, Scout, Starter, Agency) and every proof pack (Burst 500,
 * Campaign 2000, Scale 7500) so Google can render price-rich search
 * results without inheriting the live Dodo drift.
 *
 * Price type is a stringified positive integer (schema.org requires
 * `price` be a string for offers and accepts the integer canonicalization
 * Google rich-results expects). Free is intentionally a "0" so the search
 * row matches the visible free card on /pricing and never reads as
 * "missing price" in the structured-data test.
 */
function pricingProductOfferJsonLd(input: {
  productName: string;
  productDescription: string;
  productUrl: string;
  priceEUR: number;
  priceValidUntilNote: string;
  sku?: string;
}): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": "Product",
    name: input.productName,
    description: input.productDescription,
    url: input.productUrl,
    ...(input.sku ? { sku: input.sku } : {}),
    brand: { "@type": "Brand", name: SITE_NAME },
    offers: {
      "@type": "Offer",
      price: String(input.priceEUR),
      priceCurrency: "EUR",
      priceValidUntil: "2030-12-31",
      availability: "https://schema.org/InStock",
      url: input.productUrl,
      seller: { "@type": "Organization", name: SITE_NAME, url: SITE_ORIGIN },
      eligibleRegion: { "@type": "Country", name: "DE" },
      category: "https://schema.org/Subscription",
      note: input.priceValidUntilNote,
    },
  } as const;
}

function planDescriptionForPricingOffer(plan: PricingPlanSlug): string {
  if (plan === "scout") {
    return "6-hour competitor monitoring for 3 watchlists, weekly brief, and 50 proof captures per month.";
  }
  if (plan === "starter") {
    return "3-hour competitor monitoring for 10 watchlists, daily and weekly briefs, and 250 proof captures per month.";
  }
  return "75 watchlists scanned every 3 hours, daily and weekly briefs, 2,500 proof captures per month, plus team seats, API and MCP access, client reports, and shared report branding.";
}

function planUsageBundleSlugForPricingOffer(plan: PricingPlanSlug): string {
  if (plan === "scout") return "scout_monthly_v1";
  if (plan === "starter") return "starter_monthly_v1";
  return "agency_monthly_v1";
}

const PRICING_OFFERS_PAGE_URL = `${SITE_ORIGIN}/pricing`;

const PRICING_FREE_OFFER = pricingProductOfferJsonLd({
  productName: PUBLISHED_FREE_PLAN_OFFER.name,
  productDescription: PUBLISHED_FREE_PLAN_OFFER.description,
  productUrl: PRICING_OFFERS_PAGE_URL,
  priceEUR: PUBLISHED_FREE_PLAN_OFFER.offerPriceEUR,
  priceValidUntilNote:
    "Published list price for the Free Five to Nine tier. No card required.",
});

const PRICING_TIER_OFFERS: Record<PricingPlanSlug, Record<string, unknown>> = {
  scout: pricingProductOfferJsonLd({
    productName: "Scout",
    productDescription: planDescriptionForPricingOffer("scout"),
    productUrl: PRICING_OFFERS_PAGE_URL,
    sku: planUsageBundleSlugForPricingOffer("scout"),
    priceEUR: PUBLISHED_PLAN_PRICES_EUR.scout.monthly,
    priceValidUntilNote:
      "Published EUR list price for the Scout monthly plan. Localized amount at checkout may differ by region and SKU.",
  }),
  starter: pricingProductOfferJsonLd({
    productName: "Starter",
    productDescription: planDescriptionForPricingOffer("starter"),
    productUrl: PRICING_OFFERS_PAGE_URL,
    sku: planUsageBundleSlugForPricingOffer("starter"),
    priceEUR: PUBLISHED_PLAN_PRICES_EUR.starter.monthly,
    priceValidUntilNote:
      "Published EUR list price for the Starter monthly plan. Localized amount at checkout may differ by region and SKU.",
  }),
  agency: pricingProductOfferJsonLd({
    productName: "Agency",
    productDescription: planDescriptionForPricingOffer("agency"),
    productUrl: PRICING_OFFERS_PAGE_URL,
    sku: planUsageBundleSlugForPricingOffer("agency"),
    priceEUR: PUBLISHED_PLAN_PRICES_EUR.agency.monthly,
    priceValidUntilNote:
      "Published EUR list price for the Agency monthly plan. Localized amount at checkout may differ by region and SKU.",
  }),
};

const USAGE_BUNDLE_SLUGS_FOR_PRICING_OFFER: ReadonlyArray<UsageBundleSlug> = [
  "proof_500",
  "proof_2000",
  "proof_7500",
];

const PRICING_BUNDLE_OFFERS: Record<UsageBundleSlug, Record<string, unknown>> = {
  proof_500: pricingProductOfferJsonLd({
    productName: TOP_UP_PACK_DISPLAY.burst_500_v1.name,
    productDescription: TOP_UP_PACK_DISPLAY.burst_500_v1.detail,
    productUrl: PRICING_OFFERS_PAGE_URL,
    sku: "burst_500_v1",
    priceEUR: PUBLISHED_BUNDLE_PRICES_EUR.proof_500,
    priceValidUntilNote:
      "Published EUR list price for the Burst 500 proof-capture pack.",
  }),
  proof_2000: pricingProductOfferJsonLd({
    productName: TOP_UP_PACK_DISPLAY.campaign_2000_v1.name,
    productDescription: TOP_UP_PACK_DISPLAY.campaign_2000_v1.detail,
    productUrl: PRICING_OFFERS_PAGE_URL,
    sku: "campaign_2000_v1",
    priceEUR: PUBLISHED_BUNDLE_PRICES_EUR.proof_2000,
    priceValidUntilNote:
      "Published EUR list price for the Campaign 2000 proof-capture pack.",
  }),
  proof_7500: pricingProductOfferJsonLd({
    productName: TOP_UP_PACK_DISPLAY.scale_7500_v1.name,
    productDescription: TOP_UP_PACK_DISPLAY.scale_7500_v1.detail,
    productUrl: PRICING_OFFERS_PAGE_URL,
    sku: "scale_7500_v1",
    priceEUR: PUBLISHED_BUNDLE_PRICES_EUR.proof_7500,
    priceValidUntilNote:
      "Published EUR list price for the Scale 7500 proof-capture pack.",
  }),
};

/**
 * schema.org Product+Offer JSON-LD payload for /pricing (#1503). Emits one
 * Product entity per tier card and per proof pack, every Offer priced in
 * EUR with stable published list values. Returned as an array so the
 * route can render it via a single `<script type="application/ld+json">`
 * with an `@graph` root. 4 tier Offers + 3 pack Offers = 7 total,
 * matching the issue's verify command threshold
 * (>= 7 occurrences of `"@type":"Offer"`).
 *
 * Order is stable: Free, Scout, Starter, Agency, Burst 500, Campaign
 * 2000, Scale 7500 — so the JSON-LD block reads in the same order as the
 * visible /pricing cards, and a regression can be spotted by reading the
 * structured data top-to-bottom.
 */
export function pricingOffersJsonLd(): ReadonlyArray<Record<string, unknown>> {
  return [
    PRICING_FREE_OFFER,
    PRICING_TIER_OFFERS.scout,
    PRICING_TIER_OFFERS.starter,
    PRICING_TIER_OFFERS.agency,
    ...USAGE_BUNDLE_SLUGS_FOR_PRICING_OFFER.map((slug) => PRICING_BUNDLE_OFFERS[slug]),
  ];
}

/**
 * schema.org Service for an indexable /ads/:domain brand page. Describes the
 * per-competitor ad-monitoring offer the page already shows: Track {domain}
 * (issue #2051 — the page's primary CTA name), the brand the page is about,
 * the canonical URL, and Five to Nine as the provider. Description must be
 * the same string as the visible meta description (brandPageDescription) —
 * never a second invented claim.
 *
 * Do not add price, rating, or availability fields. The page says the watch
 * is free, but prices live in Dodo and must not be hardcoded in structured
 * data (same rule as organizationJsonLd).
 */
export function adsPageServiceJsonLd(input: {
  brandName: string;
  domain: string;
  description: string;
  pathname: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Service",
    name: `Track ${input.domain}`,
    description: input.description,
    url: canonicalUrl(input.pathname),
    provider: { "@type": "Organization", name: SITE_NAME, url: SITE_ORIGIN },
    about: { "@type": "Organization", name: input.brandName },
  } as const;
}

/**
 * schema.org `Dataset` for the public Offer Timeline (`/timeline/:domain`).
 *
 * The timeline is the uncopyable-history asset: a dated, source-linked change
 * ledger for one watched competitor, built from stored `landing_page_snapshot`
 * rows. Wrapping it in `Dataset` JSON-LD lets answer engines (GEO) address and
 * cite it as original data — the highest-leverage play in category-research
 * Bet 3 (issue #964).
 *
 * Every field mirrors what the page itself shows or stores — nothing invented:
 * - `datePublished`: the ISO timestamp of the FIRST stored snapshot (the day
 *   the ledger opened for this domain). Omitted when there are no entries.
 * - `dateModified`: the ISO timestamp of the LAST stored snapshot (the most
 *   recent capture the page renders). Omitted when there are no entries.
 * - `license`: the operating terms URL that governs reuse of the dataset —
 *   the same `/terms` the page footer links. Not a Creative Commons grant the
 *   terms do not make.
 * - `distribution`: a `DataDownload` pointing at the timeline's canonical URL
 *   as `text/html`, so an answer engine can fetch the citable surface itself.
 *
 * Emitted ONLY on indexable timeline pages (the route gates this on
 * `noindex === false`); a noindex shell never carries the Dataset.
 */
export function offerTimelineDatasetJsonLd(input: {
  brandName: string;
  domain: string;
  description: string;
  pathname: string;
  datePublished: string | null;
  dateModified: string | null;
}) {
  const dataset: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Dataset",
    name: `${input.brandName} offer timeline`,
    description: input.description,
    url: canonicalUrl(input.pathname),
    isAccessibleForFree: true,
    keywords: [
      input.domain,
      "offer timeline",
      "landing page changes",
      "competitor monitoring",
    ],
    creator: { "@type": "Organization", name: SITE_NAME, url: SITE_ORIGIN },
    publisher: { "@type": "Organization", name: SITE_NAME, url: SITE_ORIGIN },
    license: canonicalUrl("/terms"),
    distribution: {
      "@type": "DataDownload",
      name: `${input.brandName} offer timeline (HTML)`,
      contentUrl: canonicalUrl(input.pathname),
      encodingFormat: "text/html",
    },
  };
  if (input.datePublished) {
    dataset.datePublished = input.datePublished;
  }
  if (input.dateModified) {
    dataset.dateModified = input.dateModified;
  }
  return dataset;
}

/**
 * `hasPart` entry a brand page (`/ads/:domain`) embeds in its `WebPage`
 * JSON-LD to point answer engines at the per-competitor Offer Timeline
 * `Dataset`. Returned as the value for `WebPage.hasPart` — schema.org accepts
 * a single `CreativeWork`/`Dataset` there.
 *
 * Only emitted when the brand page is indexable AND a stored timeline exists
 * (the route already links the timeline section in that case). The URL is the
 * timeline's canonical URL; the type is `Dataset` so the relationship reads as
 * "this brand page has a citable dataset of its offer history".
 */
export function brandPageTimelineHasPart(input: {
  domain: string;
  brandName: string;
}) {
  const pathname = `/timeline/${input.domain}`;
  return {
    "@type": "Dataset",
    name: `${input.brandName} offer timeline`,
    url: canonicalUrl(pathname),
  } as const;
}

/**
 * Props for a JSON-LD <script> tag. Escapes `<` so page data can never break
 * out of the script element.
 */
export function jsonLdScriptProps(data: unknown) {
  return {
    type: "application/ld+json",
    dangerouslySetInnerHTML: {
      __html: JSON.stringify(data).replace(/</g, "\\u003c"),
    },
  } as const;
}

export const SITEMAP_PATHS = [
  "/",
  "/search",
  // Issue #1417: /brands is the hub that links the otherwise-orphaned /ads/*
  // pages to each other — adding it to the sitemap gives crawlers a direct
  // path to the full indexable brand surface (and Google an internal-link
  // graph instead of sitemap-only orphan pages).
  "/brands",
  // Issue #2143: /briefs/weekly publishes the last 7 days of stored offer
  // moves across sitemap-indexable brands. One static entry (like /brands):
  // the page renders an honest quiet state instead of noindexing when
  // nothing moved, so it never serves a noindex page from the sitemap.
  "/briefs/weekly",
  // Issue #2136: /sample-brief publishes a real stored Monday brief for the
  // newest indexable brand. One static entry: the page renders an honest
  // quiet-brief variant when no brand has a stored event, so it never serves
  // a noindex page from the sitemap.
  "/sample-brief",
  // Issue #2043: /llms-full.txt is the public full-text AEO feed of tracked-
  // brand dated offer/proof/change records. Served by workers/app.ts (the
  // route in app/routes/llms-full.txt.ts is a registration-only stub so the
  // route-registry canary passes). Listed here so crawlers discover it from
  // the sitemap; the feed degrades to an honest empty 200 when no brand has
  // a proof-complete capture, so it never serves a noindex page.
  "/llms-full.txt",
  // Issue #2152: /guides/* how-to cluster. One static entry — the guide is
  // stable long-form copy, so it never serves a noindex shell.
  "/guides/how-to-track-competitor-ads",
  // Issue #2867: second guide — the "monitor a competitor's Meta Ad Library"
  // watch-over-time intent. Stable long-form copy, never a noindex shell.
  "/guides/how-to-monitor-meta-ad-library",
  "/compare",
  "/compare/meta-ad-library",
  // /compare/visualping, /compare/foreplay, and /compare/visualping-ad-library
  // are DROPPED from the sitemap (issues #1481, #1548): each is a duplicate
  // that canonicals to its more specific sibling winner. The winner of each
  // pair stays listed below.
  "/compare/visualping-ad-libraries",
  "/compare/spyland",
  "/compare/pulzifi",
  "/compare/foreplay-spyder",
  "/compare/panoramata",
  "/compare/adspyder",
  "/compare/adspy",
  // BET 8 switch/intent pages (issue #2081). Production /sitemap.xml is
  // buildSitemapXml → ROOT_SITEMAP_STATIC_ENTRIES, which is this list minus
  // locale prefixes. lastmod is deliberately omitted: these pages have no
  // per-page content timestamp, and inventing one fails the #2031 honesty
  // clause. Keep both in this list; the #2081 canary fails if any drop.
  "/switch/panoramata",
  "/switch/visualping",
  "/competitor-monitoring",
  // Issue #2144: agency audience page (roster math + sourced Agency-vs-
  // Foreplay line). EN-only; no locale cluster.
  "/for-agencies",
  "/sneaker-resale",
  "/de/sneaker-resale",
  "/ja/sneaker-resale",
  "/pt-br/sneaker-resale",
  // Issue #1570: the locale-prefixed buyer-surface cluster (`/de/pricing`,
  // `/ja/help`, `/de/compare/panoramata`, `/de/search`, `/de/ads/nike.com`,
  // ...) was REMOVED from the sitemap. Those pages serve byte-identical
  // English copy with `lang="en"` and `canonical` -> the EN twin, so
  // listing them as dozens of distinct `<loc>` entries told Google they
  // were dozens of indexable surfaces — a duplicate-content doorway
  // pattern that burned crawl budget and split PageRank. They stay
  // reachable (200, canonical->EN) but are no longer advertised as
  // indexable. The genuinely translated sneaker-resale cluster
  // (`/de/sneaker-resale` etc., listed above) stays in the sitemap because
  // its content differs per locale.
  // Canonical Ad Aggression Score methodology page (issue #2022). Path history:
  // /methodology/ad-aggression-score (#960) -> /ad-aggression (#1263) ->
  // /methodology (#2022). The older paths 301-redirect here so any indexed
  // link keeps its equity; /proof is the legacy capture-rules canonical kept
  // out of the sitemap since it 301s to /capture-rules.
  "/capture-rules",
  // Issue #2026: the buyer-facing "no phantom changes" guarantee page. Same
  // rules source as /capture-rules, framed for a prospect evaluating a plan.
  "/no-phantom-changes",
  "/methodology",
  "/pricing",
  "/help",
  "/docs",
  "/api/docs",
  // Issue #2125: /mcp/setup is the public one-paste MCP connector setup page
  // (BET 6). It is live 200 and indexable (no noindex, canonical self) but
  // was missing from every discovery surface — Google and llms.txt consumers
  // could not find the shipped connector. One static entry: the page is
  // stable long-form copy, so it never serves a noindex shell.
  "/mcp/setup",
  "/status",
  "/changelog",
  "/trust",
  "/privacy",
  "/terms",
] as const;

/**
 * Public action surfaces that carry `<meta name="robots" content="noindex">`
 * and must stay OUT of the sitemap. These are conversion/auth entries (signup,
 * login, magic-link, password-reset, billing portal), not reading surfaces —
 * indexing them would leak the auth surface, waste crawl budget, and let the
 * signup page compete with the homepage `/` for branded "five to nine"
 * queries. Each route's `meta` carries the noindex tag itself so a future
 * accidental re-add to the sitemap still produces a noindex page; this set is
 * the sitemap-side guard that the two never overlap.
 */
export const NOINDEX_ACTION_SURFACES = [
  "/auth/signup",
] as const;

/**
 * A sitemap `<url>` entry with optional metadata. `lastmod` is an ISO 8601
 * date (YYYY-MM-DD). `changefreq` and `priority` were removed: Google has
 * ignored both for years, so emitting them was maintenance surface that
 * produced nothing.
 */
export interface SitemapEntry {
  path: string;
  lastmod?: string;
  /** Number of non-demo ads backing an /ads/:domain entry; used by llms.txt. */
  adCount?: number;
  /** ISO timestamp of the underlying cache fetch; used by llms.txt. */
  fetchedAt?: string;
}

/**
 * Static funnel paths. lastmod is deliberately omitted on static paths — the
 * build has no per-page content timestamp, and inventing one would be a false
 * freshness claim. Dynamic /ads/:domain brand pages carry a real lastmod from
 * their cache fetched_at.
 */

/**
 * Dated entries on the public /changelog page, newest first (issue #2297).
 * This is the data source for the /changelog sitemap `lastmod` — the sitemap
 * derives the newest date here at render time instead of hardcoding one, so
 * the sitemap stays fresh after the next changelog merge without a manual
 * edit. It MUST stay in sync with the `<PublicDocBlock title="YYYY-MM-DD">`
 * literals in app/routes/changelog.tsx; tests/changelog-staleness.test.ts
 * enforces that the two never drift.
 */
export const CHANGELOG_ENTRY_DATES: readonly string[] = [
  "2026-09-06",
  "2026-09-05",
  "2026-08-30",
  "2026-08-29",
  "2026-08-28",
  "2026-08-27",
  "2026-08-26",
  "2026-08-25",
  "2026-08-22",
  "2026-08-10",
  "2026-07-20",
  "2026-06-15",
  "2026-06-13",
];

export const SITEMAP_STATIC_ENTRIES: readonly SitemapEntry[] = SITEMAP_PATHS.map(
  (path) => ({ path }),
);

/**
 * Root sitemap static entries: the EN funnel set MINUS every buyer-surface
 * locale-prefixed path (issue #1561). Each `/<locale>/...` path lives only in
 * its own `/<locale>/sitemap.xml` (see `staticSitemapEntriesForLocale` in
 * app/lib/sitemap.server.ts), so a URL is never listed twice across the root
 * and locale sitemaps — which would fragment crawl budget and split PageRank
 * across byte-identical duplicates. `/ja/sneaker-resale` and
 * `/pt-br/sneaker-resale` are covered by their served `/ja/sitemap.xml` /
 * `/pt-br/sitemap.xml`; `/de/sneaker-resale` by `/de/sitemap.xml`. Since
 * issue #2017 (Option A) robots.txt advertises those locale sitemaps so the
 * URLs are reachable from a crawler entry point. The bare
 * `/{locale}` index is (and stays) absent — its canonical points at `/`.
 */
export const ROOT_SITEMAP_STATIC_ENTRIES: readonly SitemapEntry[] =
  SITEMAP_STATIC_ENTRIES.filter(
    (entry) =>
      !BUYER_SURFACE_LOCALE_IDS.some((locale) =>
        entry.path.startsWith(`/${locale}/`),
      ),
  );

/**
 * Render a sitemap urlset from an ordered entry list. Single builder shared by
 * the static fallback (`SITEMAP_XML` below, used when there is no D1 / no
 * dynamic data) and the production sitemap, which appends dynamic /ads/:domain
 * brand-page entries — see `buildSitemapXml` in app/lib/sitemap.server.ts — so
 * the two can never drift.
 */
export function renderSitemapXml(entries: readonly SitemapEntry[]): string {
  const urlBlocks = entries.map((entry) => {
    const children = [`<loc>${canonicalUrl(entry.path)}</loc>`];
    if (entry.lastmod) {
      children.push(`<lastmod>${entry.lastmod}</lastmod>`);
    }
    return `  <url>${children.join("")}</url>`;
  });
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlBlocks.join("\n")}
</urlset>
`;
}

// /ads/:domain BRAND PAGES ARE NOT IN THIS STATIC LIST — the set is dynamic.
// They are indexable by default (PUBLIC_BRAND_PAGES_INDEXABLE unset or "1";
// "0" is the emergency noindex brake), but the honest-shell, demo-sourced,
// and stale (>7 days) states always self-noindex — see
// app/routes/ads.$domain.tsx. The live sitemap (workers/app.ts) appends
// dynamic /ads/:domain entries generated from discovery_cache_entry rows that
// would render the indexable state (public_search route context, non-demo
// source, ads present, fetched_at within the 7-day freshness window) so we
// never sitemap a page that serves noindex or the "haven't checked recently"
// shell — crawl budget only goes to pages with real cached ads. The read is a
// bounded cache read at sitemap-render time (see app/lib/sitemap.server.ts);
// sitemap generation never triggers live discovery. This static XML is the
// no-DB fallback only.
const SITEMAP_XML = renderSitemapXml(ROOT_SITEMAP_STATIC_ENTRIES);

// Keep /share/ CRAWLABLE on purpose: shared reports are de-indexed via the
// `x-robots-tag: noindex, nofollow` header set in workers/security-headers.ts,
// and crawlers can only see that header if robots.txt allows the fetch.
// Adding `Disallow: /share/` here would block the crawl and let Google index
// bare /share URLs from external links anyway ("indexed, though blocked by
// robots.txt" zombies). Do NOT "fix" this by disallowing /share/.
// "Disallow: /app/" alone does not cover the bare "/app" dashboard URL
// (trailing-slash prefix rules require the slash). "/app$" closes that for
// Google/Bing, which honor the $ end-of-URL anchor; crawlers that don't
// treat the line as a harmless literal, and "/app/" still covers subpaths.
// A bare "Disallow: /app" is NOT used because it would also block any future
// public path starting with "app" (e.g. /apply).
// AI crawler policy — decision recorded in docs/ai-crawler-policy.md
// ("answers yes, training no"): search and AI-answer/reference engines are
// welcome, while AI training/fine-tuning crawlers are denied (ai-train=no).
// The Cloudflare edge managed robots.txt is the SOLE source for the AI-training
// deny list (issue #1459). Do not re-add an AI-training Disallow block here.
// Google-Extended is a control token for Gemini Apps / Vertex grounding AND
// Gemini training (Google crawler docs). It is NOT in AI_TRAINING_CRAWLERS:
// issue #2061 allows it on the public proof surface so Gemini grounding / AI
// Overviews can use the Search index. Grounding is search/reference use, which
// the content-signal already grants (`search=yes, use=reference`). ai-train=no
// is not weakened: training-only bots stay denied at the zone.
// Single source of truth for the training-crawler deny list (shared with the
// llms.txt "AI access" section in app/lib/public-markdown.ts).
export const AI_TRAINING_CRAWLERS = [
  "Amazonbot",
  "Applebot-Extended",
  "Bytespider",
  "CCBot",
  "ClaudeBot",
  "CloudflareBrowserRenderingCrawler",
  "GPTBot",
  "meta-externalagent",
] as const;

// Explicit AEO allow-list (issue #2061). Named groups, not just the wildcard,
// so the posture is intentional. Cloudflare managed robots prepends
// `User-agent: Google-Extended / Disallow: /`; Google merges same-agent groups
// and, on equal path length, uses the least restrictive rule, so `Allow: /`
// here overrides that prepended Disallow.
export const GROUNDING_ENGINES = [
  "Google-Extended",
  "OAI-SearchBot",
  "PerplexityBot",
] as const;

/**
 * Locales whose served `/<locale>/sitemap.xml` actually carries indexable
 * entries (issue #2017, Option A per the orchestrator decision on #1561).
 * robots.txt advertises ONLY these. Since issue #2294 every buyer-surface
 * locale feed is derived from the buyer-surface cluster that serves 200
 * under every locale prefix, so all five locales (de, ja, pt-br, fr, es)
 * carry a non-empty sitemap and are advertised. Derived from
 * `BUYER_SURFACE_LOCALE_IDS` so a future locale is advertised automatically.
 */
export const LOCALE_SITEMAP_LOCALES: readonly BuyerSurfaceLocaleId[] = [
  ...BUYER_SURFACE_LOCALE_IDS,
];

/**
 * Every sitemap URL robots.txt advertises: the root sitemap plus one
 * non-empty locale sitemap per translated-entries locale (issue #2017).
 * The locale sitemaps are the ONLY path by which `/de/sneaker-resale`,
 * `/ja/sneaker-resale`, and `/pt-br/sneaker-resale` become discoverable —
 * #1561 keeps locale-prefixed URLs out of the root sitemap, so without these
 * `Sitemap:` lines those acquisition pages have no sitemap path at all.
 * Exposed for the llms.txt↔reachable-sitemap sync canary
 * (tests/seo/llms-sitemap-reachable-sync.test.ts).
 */
export const ADVERTISED_SITEMAP_URLS: readonly string[] = [
  canonicalUrl("/sitemap.xml"),
  ...LOCALE_SITEMAP_LOCALES.map((locale) =>
    canonicalUrl(`/${locale}/sitemap.xml`),
  ),
];

const LOCALE_SITEMAP_LINES = LOCALE_SITEMAP_LOCALES.map(
  (locale) => `Sitemap: ${canonicalUrl(`/${locale}/sitemap.xml`)}`,
).join("\n");

// Shared by the wildcard group and every grounding-engine group. Private
// /app/**, /api/**, /export/** stay disallowed; /share/ stays crawlable so
// crawlers can see its noindex header.
const PUBLIC_ALLOW_RULES = `Allow: /api/docs
Disallow: /app$
Disallow: /app/
Disallow: /export/
Disallow: /api/
# /share/ stays crawlable so crawlers can see its noindex header.
Allow: /`;

const GROUNDING_BLOCKS = GROUNDING_ENGINES.map(
  (agent) => `User-agent: ${agent}
${PUBLIC_ALLOW_RULES}`,
).join("\n\n");

const ROBOTS_TXT = `# Grounding / AI-answer engines (Google-Extended, OAI-SearchBot, PerplexityBot)
# are allowed on the public proof surface. Grounding is search/reference use
# (content-signal search=yes, use=reference), not training. AI training crawlers
# stay denied at the zone by Cloudflare managed robots (ai-train=no). Policy:
# docs/ai-crawler-policy.md. Issue #2061 / #1459: do not re-add a training
# Disallow block here.
#
# Issue #2043: /llms-full.txt is the full-text AEO feed of tracked-brand dated
# offer/proof/change records. Allowed below by Allow: / and listed in the
# sitemap; AI answer engines may fetch it for citation.

User-agent: *
${PUBLIC_ALLOW_RULES}
Sitemap: ${canonicalUrl("/sitemap.xml")}
${LOCALE_SITEMAP_LINES}

# Grounding / AI-answer engines — explicit, not just wildcard (issue #2061).
# Google-Extended Allow: / overrides the Cloudflare managed Disallow: / because
# Google merges same-agent groups and prefers the least restrictive equal-length rule.
${GROUNDING_BLOCKS}
`;

const SOCIAL_CARD_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-labelledby="title desc">
  <title id="title">Five to Nine</title>
  <desc id="desc">Competitor offer monitoring workspace preview for Five to Nine.</desc>
  <defs>
    <linearGradient id="sky" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0" stop-color="#52c9df"/>
      <stop offset="0.42" stop-color="#7f5cff"/>
      <stop offset="0.72" stop-color="#ff5f74"/>
      <stop offset="1" stop-color="#f9c37b"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="630" fill="url(#sky)"/>
  <path d="M0 420 L1200 300 L1200 630 L0 630 Z" fill="#fff"/>
  <g opacity="0.23" stroke="#fff" stroke-width="1">
    <path d="M0 96H1200"/><path d="M0 192H1200"/><path d="M0 288H1200"/><path d="M0 384H1200"/>
    <path d="M120 0V630"/><path d="M240 0V630"/><path d="M360 0V630"/><path d="M480 0V630"/>
    <path d="M600 0V630"/><path d="M720 0V630"/><path d="M840 0V630"/><path d="M960 0V630"/><path d="M1080 0V630"/>
  </g>
  <g font-family="Inter, Arial, sans-serif" font-weight="800">
    <text x="86" y="92" fill="#fff" font-size="42">Five to Nine</text>
    <text x="86" y="222" fill="#07111a" font-size="78">Know when competitors</text>
    <text x="86" y="318" fill="#07111a" font-size="78">change the offer.</text>
  <text x="88" y="418" fill="#344052" font-size="34" font-weight="600">Watch ads and landing pages with sources.</text>
    <rect x="780" y="118" width="340" height="330" rx="34" fill="#ffffff" opacity="0.9"/>
    <text x="818" y="180" fill="#07111a" font-size="28">Competitor changes</text>
    <path d="M820 260 L884 230 L944 246 L1014 186 L1080 206" fill="none" stroke="#635bff" stroke-width="7" stroke-linecap="round"/>
    <text x="818" y="340" fill="#425466" font-size="26" font-weight="700">Offer changed</text>
    <text x="818" y="386" fill="#425466" font-size="26" font-weight="700">Landing page saved</text>
    <text x="818" y="432" fill="#425466" font-size="26" font-weight="700">Saved evidence</text>
  </g>
</svg>
`;

export function publicSeoFileForPathname(pathname: string) {
  if (pathname === "/robots.txt") {
    return {
      body: ROBOTS_TXT,
      contentType: "text/plain; charset=utf-8",
      cacheControl: "public, max-age=3600",
    };
  }

  if (pathname === "/sitemap.xml") {
    return {
      body: SITEMAP_XML,
      contentType: "application/xml; charset=utf-8",
      cacheControl: "public, max-age=3600",
    };
  }

  if (pathname === LEGACY_SOCIAL_CARD_PATH) {
    return {
      body: SOCIAL_CARD_SVG,
      contentType: "image/svg+xml; charset=utf-8",
      cacheControl: "public, max-age=86400",
    };
  }

  return null;
}
