self-hosted-runner:
  labels:
    - vps-verify

config-variables: null

paths:
  .github/workflows/**/*.yml:
    ignore:
      - '^unexpected key "queue" for "concurrency" section\. expected one of "cancel-in-progress", "group"$'
      - '^unknown permission scope "vulnerability-alerts"\.'