-- 0048_drop_rate_limit_events.sql — drop the dead rate_limit_events table.
-- Issue #7194, parent audit #7080.
--
-- Why: 0001_rebuild.sql created the table and nothing on origin/main touches it.
-- No module in app/, workers/ or e2e/ names it, no route, workflow or MCP tool
-- reads or writes it, and no migration after 0001 alters it. Production held 0
-- rows when the parent audit measured it (#7194). The index 0001 created on it
-- goes with the table: SQLite drops an index with its table.
--
-- Its own file, never an edit to 0001_rebuild.sql: d1_migrations tracks by
-- filename and production applied 0001 on 2026-09-21, so a statement appended
-- there executes in no later deploy and nowhere else (precedent
-- migrations/0012_drop_legacy_tables.sql, #4039).
--
-- Restore plan: no down-migration exists, so the only way back is
-- wrangler d1 time-travel restore with a bookmark before this file applies
-- (docs/REBUILD-SCHEMA.md). That restore rewrites the whole database to that
-- point, losing every write since; it is Nish's call and not a routine rollback.
--
-- One statement and nothing else, per the D1 expand/contract rule: this PR
-- carries no code change, so a drop is the whole of it. D1 has no
-- down-migration, so the table cannot come back except through a newer file
-- that recreates it. IF EXISTS keeps the file re-runnable against a local or
-- test D1 built by the same chain.
--
-- Number: 0048 is the next free number on origin/main, which ends at 0047.
-- tests/migration-numbers.test.ts and tests/ads/parked-sources.migration.test.ts
-- require files numbered 1..N with no gap, so a file that skips a number is
-- red on its own PR. This is the same correction 96208f059 reverted: "take
-- migration 0031 so older open PRs keep 0027-0030" was reverted on main because
-- the contiguity gates forbid gaps. An open PR that needs this number renumbers
-- at rework time.
DROP TABLE IF EXISTS rate_limit_events;
