import { type RouteConfig, layout, route } from "@react-router/dev/routes";

export default [
  route("login", "routes/login.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("robots.txt", "routes/robots[.]txt.ts"),
  route("sitemap.xml", "routes/sitemap[.]xml.ts"),
  layout("routes/app-layout.tsx", [
    route("app", "routes/app.home.tsx"),
    route("app/competitors", "routes/app.competitors.tsx"),
    route("app/competitors/:entityId", "routes/app.competitor.tsx"),
    route("app/alerts", "routes/app.alerts.tsx"),
    route("app/brief/:digestId?", "routes/app.brief.tsx"),
    route("app/settings", "routes/app.settings.tsx"),
    route("app/settings/agents", "routes/settings.agents.tsx"),
    route("app/settings/brief-pause", "routes/settings.brief-pause.ts"),
  ]),
  route("app/share.png", "routes/app.share[.]png.ts"),
  route("app/changes/:signalId/:side", "routes/app.change-shot.ts"),
  route("app/alerts/shot/:signalId/:which", "routes/app.alerts.shot.ts"),
  route("app/logos/:entityId", "routes/app.logo.ts"),
  route("u/:token", "routes/u.$token.tsx"),
  route("api/health", "routes/api.health.ts"),
  route("api/auth/*", "routes/api.auth.$.ts"),
  route("mcp", "routes/mcp.ts"),
  route("oauth/authorize", "routes/oauth.authorize.tsx"),
  route("api/v1/brief", "routes/api.v1.brief.ts"),
  route("api/v1/competitors", "routes/api.v1.competitors.ts"),
  route("api/v1/competitors/:competitorId", "routes/api.v1.competitors.$competitorId.ts"),
  route("api/v1/alerts", "routes/api.v1.alerts.ts"),
  route("api/v1/standing", "routes/api.v1.standing.ts"),
  route("api/v1/openapi.json", "routes/api.v1.openapi[.]json.ts"),
  route("onboarding", "routes/onboarding.tsx"),
  route("*", "routes/unmatched.tsx"),
  route("onboarding/competitors", "routes/onboarding.competitors.tsx"),
  route("design/capture-plates", "routes/design.capture-plates.tsx"),
  route("design/competitor", "routes/design.competitor.tsx"),
  route("llms.txt", "routes/llms[.]txt.ts"),
  route("design/landing", "routes/landing.tsx"),
  route("onboarding/identity", "routes/onboarding.identity.tsx"),
] satisfies RouteConfig;
