import {
  type RouteConfig,
  index,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/marketing.tsx"),
  route("search", "routes/search.tsx"),
  route("help", "routes/help.tsx"),
  route("docs", "routes/docs.tsx"),
  route("api/docs", "routes/api.docs.tsx"),
  route("status", "routes/status.tsx"),
  route("changelog", "routes/changelog.tsx"),
  route("trust", "routes/trust.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("unsubscribe", "routes/unsubscribe.tsx"),
  route("auth/login", "routes/auth.login.tsx"),
  route("auth/signup", "routes/auth.signup.tsx"),
  route("auth/logout", "routes/auth.logout.ts"),
  route("auth/stytch/oauth", "routes/auth.stytch.oauth.ts"),
  route("auth/stytch/callback", "routes/auth.stytch.callback.tsx"),
  route("auth/stytch/confirm", "routes/auth.stytch.confirm.tsx"),
  route("auth/forgot-password", "routes/auth.forgot-password.tsx"),
  route("auth/reset-password", "routes/auth.reset-password.tsx"),
  route("api/auth/*", "routes/api.auth.$.ts"),
  route("api/billing/dodo/checkout", "routes/api.billing.dodo.checkout.ts"),
  route("api/billing/dodo/canary", "routes/api.billing.dodo.canary.ts"),
  route("api/billing/dodo/portal", "routes/api.billing.dodo.portal.ts"),
  route("api/demo-proof", "routes/api.demo-proof.ts"),
  route("api/mcp", "routes/api.mcp.ts"),
  route("api/v1", "routes/api.v1.ts"),
  route("api/v1/:resourceType/:resourceId", "routes/api.v1.$resourceType.$resourceId.ts"),
  route("api/pricing-preview", "routes/api.pricing-preview.ts"),
  route("api/webhooks/dodo", "routes/api.webhooks.dodo.ts"),
  route("api/delivery-status/:provider", "routes/api.delivery-status.$provider.ts"),
  route("api/health", "routes/api.health.ts"),
  route("api/launch-readiness", "routes/api.launch-readiness.ts"),
  route("api/launch-readiness/canary", "routes/api.launch-readiness.canary.ts"),
  route("app/onboard", "routes/app.onboard.tsx"),
  route("compare/magicbrief", "routes/compare.magicbrief.tsx"),
  route("team/accept", "routes/team.accept.tsx"),
  route("share/:token", "routes/share.$token.tsx"),
  route("export/:resourceType/:resourceId", "routes/export.$resourceType.$resourceId.tsx"),
  route("app", "routes/app-layout.tsx", [
    index("routes/app.dashboard.tsx"),
    route("collections", "routes/app.collections.tsx"),
    route("watchlists", "routes/app.watchlists.tsx"),
    route("digests", "routes/app.digests.tsx"),
    route("shares", "routes/app.shares.tsx"),
    route("billing", "routes/app.billing.tsx"),
    route("account", "routes/app.account.tsx"),
    route("team", "routes/app.team.tsx"),
    route("sources", "routes/app.sources.tsx"),
    route("ops", "routes/app.ops.tsx"),
    route("reports/:id", "routes/app.reports.tsx"),
  ]),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
